[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
VITE_API_URL = "https://espaco88backend-production.up.railway.app"